package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"zeus/net/demo/proto/test"

	"zeus/net/server"
)

// 注册消息.
func RegMsg_hello(svr *server.Server) {
	regMsg2ID_hello(svr)
	regMsgCreators_hello(svr)
}

// 注册消息ID, 用于发送消息.
func regMsg2ID_hello(svr *server.Server) {
	// [ServerToClient] 注册发送的消息。需要从类型获取ID。
	svr.RegMsg2ID(&test.SayResponse{}, 11002)

}

// 注册消息创建器，用于接收数据后创建消息。
func regMsgCreators_hello(svr *server.Server) {
	// [ClientToServer] 注册接收的消息。需要从ID创建消息。
	svr.RegMsgCreator(11001, func() server.IMsg { return &test.SayRequest{} })

}
