package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"zeus/net/demo/proto/test"

	"zeus/net/msg2id"
)

func RegMsg2ID_hello(m *msg2id.Msg2ID) {
	// [ClientToServer] 注册发送的消息。需要从类型获取ID。
	m.RegMsg2ID(&test.SayRequest{}, 11001)

}
