//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: wilds.proto
namespace usercmd
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLogin")]
  public partial class MsgLogin : global::ProtoBuf.IExtensible
  {
    public MsgLogin() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoginResult")]
  public partial class MsgLoginResult : global::ProtoBuf.IExtensible
  {
    public MsgLoginResult() {}
    
    private bool _ok;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ok", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ok
    {
      get { return _ok; }
      set { _ok = value; }
    }
    private ulong _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayer> _others = new global::System.Collections.Generic.List<usercmd.MsgPlayer>();
    [global::ProtoBuf.ProtoMember(4, Name=@"others", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayer> others
    {
      get { return _others; }
    }
  
    private uint _frame;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private uint _ballId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ballId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ballId
    {
      get { return _ballId; }
      set { _ballId = value; }
    }
    private readonly global::System.Collections.Generic.List<usercmd.MsgBall> _balls = new global::System.Collections.Generic.List<usercmd.MsgBall>();
    [global::ProtoBuf.ProtoMember(9, Name=@"balls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgBall> balls
    {
      get { return _balls; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayerBall> _playerballs = new global::System.Collections.Generic.List<usercmd.MsgPlayerBall>();
    [global::ProtoBuf.ProtoMember(10, Name=@"playerballs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayerBall> playerballs
    {
      get { return _playerballs; }
    }
  
    private uint _leftTime = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"leftTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint leftTime
    {
      get { return _leftTime; }
      set { _leftTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTop")]
  public partial class MsgTop : global::ProtoBuf.IExtensible
  {
    public MsgTop() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayer> _players = new global::System.Collections.Generic.List<usercmd.MsgPlayer>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayer> players
    {
      get { return _players; }
    }
  
    private uint _EndTime = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint EndTime
    {
      get { return _EndTime; }
      set { _EndTime = value; }
    }
    private uint _Rank = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Rank
    {
      get { return _Rank; }
      set { _Rank = value; }
    }
    private uint _KillNum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"KillNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint KillNum
    {
      get { return _KillNum; }
      set { _KillNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneTCP")]
  public partial class MsgSceneTCP : global::ProtoBuf.IExtensible
  {
    public MsgSceneTCP() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.BallEat> _eats = new global::System.Collections.Generic.List<usercmd.BallEat>();
    [global::ProtoBuf.ProtoMember(1, Name=@"eats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.BallEat> eats
    {
      get { return _eats; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgBall> _adds = new global::System.Collections.Generic.List<usercmd.MsgBall>();
    [global::ProtoBuf.ProtoMember(2, Name=@"adds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgBall> adds
    {
      get { return _adds; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _removes = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"removes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> removes
    {
      get { return _removes; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.HitMsg> _hits = new global::System.Collections.Generic.List<usercmd.HitMsg>();
    [global::ProtoBuf.ProtoMember(4, Name=@"hits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.HitMsg> hits
    {
      get { return _hits; }
    }
  
    private readonly global::System.Collections.Generic.List<usercmd.MsgPlayerBall> _addPlayers = new global::System.Collections.Generic.List<usercmd.MsgPlayerBall>();
    [global::ProtoBuf.ProtoMember(5, Name=@"addPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.MsgPlayerBall> addPlayers
    {
      get { return _addPlayers; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _removePlayers = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"removePlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> removePlayers
    {
      get { return _removePlayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneUDP")]
  public partial class MsgSceneUDP : global::ProtoBuf.IExtensible
  {
    public MsgSceneUDP() {}
    
    private readonly global::System.Collections.Generic.List<usercmd.BallMove> _moves = new global::System.Collections.Generic.List<usercmd.BallMove>();
    [global::ProtoBuf.ProtoMember(1, Name=@"moves", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<usercmd.BallMove> moves
    {
      get { return _moves; }
    }
  
    private uint _frame;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayer")]
  public partial class MsgPlayer : global::ProtoBuf.IExtensible
  {
    public MsgPlayer() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _IsLive = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IsLive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsLive
    {
      get { return _IsLive; }
      set { _IsLive = value; }
    }
    private usercmd.MsgPlayerSnap _SnapInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"SnapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public usercmd.MsgPlayerSnap SnapInfo
    {
      get { return _SnapInfo; }
      set { _SnapInfo = value; }
    }
    private uint _ballId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"ballId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ballId
    {
      get { return _ballId; }
      set { _ballId = value; }
    }
    private uint _curexp = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"curexp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curexp
    {
      get { return _curexp; }
      set { _curexp = value; }
    }
    private uint _curmp = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"curmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curmp
    {
      get { return _curmp; }
      set { _curmp = value; }
    }
    private uint _curhp = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"curhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curhp
    {
      get { return _curhp; }
      set { _curhp = value; }
    }
    private int _bombNum = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bombNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bombNum
    {
      get { return _bombNum; }
      set { _bombNum = value; }
    }
    private int _hammerNum = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"hammerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hammerNum
    {
      get { return _hammerNum; }
      set { _hammerNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAddPlayer")]
  public partial class MsgAddPlayer : global::ProtoBuf.IExtensible
  {
    public MsgAddPlayer() {}
    
    private usercmd.MsgPlayer _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRefreshPlayer")]
  public partial class MsgRefreshPlayer : global::ProtoBuf.IExtensible
  {
    public MsgRefreshPlayer() {}
    
    private usercmd.MsgPlayer _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRemovePlayer")]
  public partial class MsgRemovePlayer : global::ProtoBuf.IExtensible
  {
    public MsgRemovePlayer() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMove")]
  public partial class MsgMove : global::ProtoBuf.IExtensible
  {
    public MsgMove() {}
    
    private int _angle;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private int _power;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRelife")]
  public partial class MsgRelife : global::ProtoBuf.IExtensible
  {
    public MsgRelife() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgS2CRelife")]
  public partial class MsgS2CRelife : global::ProtoBuf.IExtensible
  {
    public MsgS2CRelife() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _frame = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private usercmd.MsgPlayerSnap _SnapInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SnapInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public usercmd.MsgPlayerSnap SnapInfo
    {
      get { return _SnapInfo; }
      set { _SnapInfo = value; }
    }
    private uint _curhp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curhp
    {
      get { return _curhp; }
      set { _curhp = value; }
    }
    private uint _curmp = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"curmp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curmp
    {
      get { return _curmp; }
      set { _curmp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDeath")]
  public partial class MsgDeath : global::ProtoBuf.IExtensible
  {
    public MsgDeath() {}
    
    private uint _maxScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxScore
    {
      get { return _maxScore; }
      set { _maxScore = value; }
    }
    private ulong _killId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"killId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong killId
    {
      get { return _killId; }
      set { _killId = value; }
    }
    private string _killName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"killName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string killName
    {
      get { return _killName; }
      set { _killName = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEndRoom")]
  public partial class MsgEndRoom : global::ProtoBuf.IExtensible
  {
    public MsgEndRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientHeartBeat")]
  public partial class ClientHeartBeat : global::ProtoBuf.IExtensible
  {
    public ClientHeartBeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgActCloseSocket")]
  public partial class MsgActCloseSocket : global::ProtoBuf.IExtensible
  {
    public MsgActCloseSocket() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCastSkill")]
  public partial class MsgCastSkill : global::ProtoBuf.IExtensible
  {
    public MsgCastSkill() {}
    
    private uint _skillid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillid
    {
      get { return _skillid; }
      set { _skillid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRun")]
  public partial class MsgRun : global::ProtoBuf.IExtensible
  {
    public MsgRun() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSceneChat")]
  public partial class MsgSceneChat : global::ProtoBuf.IExtensible
  {
    public MsgSceneChat() {}
    
    private string _Msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Msg
    {
      get { return _Msg; }
      set { _Msg = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerSnap")]
  public partial class MsgPlayerSnap : global::ProtoBuf.IExtensible
  {
    public MsgPlayerSnap() {}
    
    private float _Snapx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Snapx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Snapx
    {
      get { return _Snapx; }
      set { _Snapx = value; }
    }
    private float _Snapy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Snapy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Snapy
    {
      get { return _Snapy; }
      set { _Snapy = value; }
    }
    private float _Angle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Angle
    {
      get { return _Angle; }
      set { _Angle = value; }
    }
    private ulong _Id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBall")]
  public partial class MsgBall : global::ProtoBuf.IExtensible
  {
    public MsgBall() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerBall")]
  public partial class MsgPlayerBall : global::ProtoBuf.IExtensible
  {
    public MsgPlayerBall() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _hp = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private uint _mp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mp
    {
      get { return _mp; }
      set { _mp = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _angle = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BallMove")]
  public partial class BallMove : global::ProtoBuf.IExtensible
  {
    public BallMove() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _angle = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private uint _face = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint face
    {
      get { return _face; }
      set { _face = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BallEat")]
  public partial class BallEat : global::ProtoBuf.IExtensible
  {
    public BallEat() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private uint _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HitMsg")]
  public partial class HitMsg : global::ProtoBuf.IExtensible
  {
    public HitMsg() {}
    
    private uint _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint source
    {
      get { return _source; }
      set { _source = value; }
    }
    private uint _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _addHp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"addHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addHp
    {
      get { return _addHp; }
      set { _addHp = value; }
    }
    private uint _curHp = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint curHp
    {
      get { return _curHp; }
      set { _curHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgTypeCmd")]
    public enum MsgTypeCmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=1001)]
      Login = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Top", Value=1002)]
      Top = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddPlayer", Value=1003)]
      AddPlayer = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemovePlayer", Value=1004)]
      RemovePlayer = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Move", Value=1006)]
      Move = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Run", Value=1007)]
      Run = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReLife", Value=1009)]
      ReLife = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Death", Value=1010)]
      Death = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EndRoom", Value=1011)]
      EndRoom = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RefreshPlayer", Value=1013)]
      RefreshPlayer = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartBeat", Value=1016)]
      HeartBeat = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneChat", Value=1020)]
      SceneChat = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActCloseSocket", Value=1021)]
      ActCloseSocket = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMsg", Value=1025)]
      ErrorMsg = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneTCP", Value=1031)]
      SceneTCP = 1031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SceneUDP", Value=1032)]
      SceneUDP = 1032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CastSkill", Value=1050)]
      CastSkill = 1050
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MapObjectConfigType")]
    public enum MapObjectConfigType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Empty", Value=0)]
      Empty = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Block", Value=1)]
      Block = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"BallType")]
    public enum BallType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Player", Value=1)]
      Player = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodBegin", Value=10)]
      FoodBegin = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodNormal", Value=11)]
      FoodNormal = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodHammer", Value=12)]
      FoodHammer = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodBomb", Value=13)]
      FoodBomb = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FoodEnd", Value=19)]
      FoodEnd = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedBegin", Value=20)]
      FeedBegin = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedNormal", Value=21)]
      FeedNormal = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FeedEnd", Value=29)]
      FeedEnd = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillBegin", Value=30)]
      SkillBegin = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillHammer", Value=31)]
      SkillHammer = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillBomb", Value=32)]
      SkillBomb = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SkillEnd", Value=39)]
      SkillEnd = 39
    }
  
}